## Formas de armazenamento de dados em memória

### Lista é um vetor, matriz de 1 dimensão em Python

In [52]:
mat = [2,3,4,5,6,7]

In [53]:
mat

[2, 3, 4, 5, 6, 7]

## Em Python, uma lista é muito versátil

  - uma lista pode receber um conjuto heterogêneo de dados  
  - já um array do numpy (vamos ver adiante) NÃO !!!

In [104]:
m2 = [1, 2, 3.5, 1/3, 'a', 'como vai você?']
m2

[1, 2, 3.5, 0.3333333333333333, 'a', 'como vai você?']

In [105]:
m2[0], m2[1:3], m2[-1]

(1, [2, 3.5], 'como vai você?')

## Qual é classe de um dado elemento?


In [106]:
type(m2[0]), type(m2[3]), type(m2[5])

(int, float, str)

In [107]:
i = 5
"O elemento '%s', na posição %d, é do tipo %s"%(str(m2[i]), i, type(m2[i]))

"O elemento 'como vai você?', na posição 5, é do tipo <class 'str'>"

## Veja como é fácil um loop (laço)

In [108]:
len(m2)

6

In [109]:
# com o for (loop) posso percorrer cada um dos elementos
for elem in m2:
    # <tab> para identar dentro de um laço
    print(elem)

1
2
3.5
0.3333333333333333
a
como vai você?


In [ ]:
# \t == tabulador
# type() - é para achar o tipo de objeto

for elem in m2:
    print('\t', elem, 'tipo:', type(elem))

## O Python começa contar do zero

In [54]:
# primeiro elemento
mat[0]

2

## Selecionando elementos:
  - os três primeiros: mat[0:3]
  - todos menos elementos

In [90]:
mat[:3]

[2, 3, 4]

In [92]:
# todos
mat

[2, 3, 4, 5, 6, 7]

In [93]:
# todos de 0 a 7 = len(mat)
mat[0:7]

[2, 3, 4, 5, 6, 7]

## Lembre-se que podemos usar np.arange() e np.linspace()
  - funções do numpy

In [57]:
# importando (carregando) a biblioteca numpy e dando apelido de np
import numpy as np

In [58]:
mat2 = np.arange(0, 21)
mat2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [94]:
# qual o comprimento de mat2
len(mat2), type(mat2)

(21, numpy.ndarray)

In [60]:
# pegando os primeiros 5 elementos
# como começa com zero vai até 5-1
mat2[0:5]

array([0, 1, 2, 3, 4])

## maneira fácil de buscar o último elemento (ciclicamente)

In [61]:
# qual o último elemento?
mat2[-1]

20

In [62]:
# pegando os 5 ultimos elementos de mat2
mat2[-5:]

array([16, 17, 18, 19, 20])

## Usando linspace: dividindo um intervalo em n pontos, incluso o primeiro e o último

- Logo, se vc criou uma lista de 1 até 20 - você terá, por exemplo, 19 divisições internas +1 inicio e +1 o fim = 21 pontos

In [63]:
mat3 = np.arange(1, 21)
mat3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
# ou da mesma forma
mat3 = np.arange(1, 21, step=1)
mat3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [65]:
# ou com linspace - 19+2 pontos
mat3 = np.linspace(1, 21, 21)
mat3

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21.])

In [66]:
# iniciar de zero tem que aumentar +1
mat3 = np.linspace(0, 21, 22)
mat3

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21.])

In [67]:
# qual o comprimento de mat3
len(mat3)

22

In [68]:
# qual o último elemento de mat3?
mat3[-1]

21.0

In [69]:
# pegando os 5 ultimos elementos de mat3
mat3[-5: ]

array([17., 18., 19., 20., 21.])

In [70]:
# Exercício: pegando os 10 ultimos elementos de mat3


## Como passar os pontos para inteiro?

In [71]:
# repare, são pontos flutuantes
type(mat3[0])

numpy.float64

## Use comprehension e a função int() - torne um inteiro

In [72]:
# se eu não faço nada continua ponto flutuante
mat4 = [x for x in mat3]
mat4[:5], type(mat4[0])

([0.0, 1.0, 2.0, 3.0, 4.0], numpy.float64)

In [73]:
# passando para interiro - repare no int(x)
mat4 = [int(x) for x in mat3]
mat4[:5], type(mat4[0])

([0, 1, 2, 3, 4], int)

## O Python conta a partir do zero (0) e descarta o último elemento len(mat)

In [74]:
mat4

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [75]:
# o print é "quase igual" ao echo da variável no jupyter
print(mat4)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


In [76]:
# não preciso colar len(mat4)
mat4[0:len(mat4)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [77]:
# vá de 0 até o fim, '0:'
mat4[0:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [78]:
# vá do 5o elemento até o fim
# é quinto ou sexto??? é sexto elemento! começa do zero
mat4[5:]

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [79]:
[i for i in range(len(mat4)) if mat4[i]==5]

[5]

## Uau o que é isto?

```
range(len(mat4))

crie uma sequencia (iterator) com o comprimento de mat4
```

### range cria um interator como np.arange cria uma lista
### range(5) = iterator(de 0 a 5)
### range(1, 5) = iterator(de 1, 4)
### range(1, 5, 2) = iterator(de 1 e 3)




In [96]:
range(5)

range(0, 5)

In [97]:
range(1,5)

range(1, 5)

In [99]:
range(1,5,2)

range(1, 5, 2)

In [101]:
# transformar iterator em lista
list(range(1,5,2))

[1, 3]

## Ao invés de range(5) --> range(len(mat|))

In [80]:
for i in range(len(mat4)):
  print(i)
  if i == 2: break

0
1
2


In [102]:
### lembre que mat4 é ...
mat4

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [81]:
## é um iterator ... uma lista rápida ... de 0 a até len(mat4)
## repare que para eu ver a list preciso colocar "list()" --> transforme em lista
list( range(len(mat4)) )

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

## Se tentar printar o iterator

In [82]:
range(len(mat4))

range(0, 22)

## Selecionar somente o número 5 e dizer qual a posição 'i'

  - o número 5 está na posição 5
  - logo, a posição 5 começa de zero = sexta posição, correto? Sim.

### Usando comprehension

In [83]:
# a resposta ainda é uma lista de um elemento
[i for i in range(len(mat4)) if mat4[i]==5]

[5]

## Para responder para um ser humano eu pego o primeiro e único elemento da lista e somo 1 (pois começa no zero)

In [84]:
posi = [i for i in range(len(mat4)) if mat4[i]==5][0] + 1
posi

6

## Posso comparar matrizes?

## mat[0:len(mat)] = mat

In [85]:
# A resposta é booleana: True ou False
mat[0:len(mat)] == mat

True

## Será que estas são duas formas de achar o último elemento?

## mat[-1] == mat[len(mat)-1]

In [86]:
mat[-1] == mat[len(mat)-1]

True

## Erro não existe o elemento len(mat)

In [87]:
mat[len(mat)]

IndexError: ignored

## Lembre-se como contornar um erro

In [103]:
try:
    mat[len(mat)]
except:
    print("O Python começa de zero e o último elmento da matriz (ou lista) é len(mat)-1")
    
mat[len(mat)-1]    

O Python começa de zero e o último elmento da matriz (ou lista) é len(mat)-1


7

## O Python às vezes faz mágica ou confunde o programador (!?)

In [110]:
mat

[2, 3, 4, 5, 6, 7]

In [111]:
mat * 3

[2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7]

In [112]:
# isto não funciona !
mat + 1

TypeError: ignored

In [113]:
mat2 = [10, 11, 12, 13, 14, 15]
mat, mat2

([2, 3, 4, 5, 6, 7], [10, 11, 12, 13, 14, 15])

## A Lista tem características próprias, e aqui mat + mat2 = union(mat, mat2)

In [114]:
mat + mat2

[2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15]

## Existe uma biblioteca MUITO RÁPIDA para manipular matrizes e cálculo com números

  - Numpy: https://numpy.org/

In [115]:
### Chamando um biblioteca em python (ou pacote = package)
import numpy as np
### chamo numpy com o apelido np

In [116]:
mat, type(mat)

([2, 3, 4, 5, 6, 7], list)

## transformando a Lista em Array (numpy)

In [117]:
matn = np.array(mat)
matn, type(matn)

(array([2, 3, 4, 5, 6, 7]), numpy.ndarray)

## A lista multiplica os elementos por n vezes

In [118]:
mat * 3

[2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7]

## O numpy não! Ele múltipla os elementos interno por n

In [119]:
matn * 3

array([ 6,  9, 12, 15, 18, 21])

## A lista não sabe somar 1 aos seus elementos

In [120]:
# erro !
mat + 1

TypeError: ignored

## O numpy sabe somar n nos elementos 

In [121]:
matn + 1

array([3, 4, 5, 6, 7, 8])

In [122]:
matn2 = np.array(mat2)
matn, matn2

(array([2, 3, 4, 5, 6, 7]), array([10, 11, 12, 13, 14, 15]))

## Fazer uma soma de elemento por elemento, ambas as listas numpy tem que ter a mesma dimensão

In [123]:
matn + matn2

array([12, 14, 16, 18, 20, 22])

## Numpy array exige que todos os elementos seja da mesma classe (type())

In [124]:
matn + ['aaa', 'bbb']

UFuncTypeError: ignored

In [126]:
## assim ...

mat5 = [1,2,4,5] + [8, 9, 10]
mat5

[1, 2, 4, 5, 8, 9, 10]

In [127]:
mat5 = np.array(mat5)
mat5

array([ 1,  2,  4,  5,  8,  9, 10])

## Como você pode obsevar uma LISTA tem um comportamento diferente que uma Lista em Numpy

## Você acha que o numpy é rápido

 - %%time é um meta-comando --> pede para calcular o tempo transcorrido para processar a célula

In [128]:
%%time

total=0

lista = np.arange(0, 1000*1000*10)
for i in lista:
    # somando 1 em total --> igual a total = total + 1
    total += i
    
print("---- fim:", total)    

---- fim: 49999995000000
CPU times: user 2.54 s, sys: 59 ms, total: 2.6 s
Wall time: 2.65 s


In [129]:
%%time

lista = np.arange(0, 1000*1000*10)
total = np.sum(lista)
    
print("---- fim:", total)

---- fim: 49999995000000
CPU times: user 21.6 ms, sys: 43.3 ms, total: 64.9 ms
Wall time: 65.3 ms


## Porque o numpy é ao menos 60 vezes mais rápido?