### Um vetor, matriz de 1 dimensão = lista em Python

In [1]:
mat = [2,3,4,5,6,7]

In [2]:
mat

[2, 3, 4, 5, 6, 7]

In [3]:
len(mat)

6

o Python começa contar do zero

In [4]:
# primeiro elemento
mat[0]

2

In [5]:
len(mat)

6

In [7]:
# erro porque o Python conta a partir do zero (0)
# o último elemento len()-1
mat[len(mat)-1]

7

In [8]:
# maneira fácil - bucar ciclicamento o anterior ao zero
mat[-1]

7

In [9]:
mat[-1] == mat[len(mat)-1]

True

### Em Python, uma lista é muito versátil

uma lista pode receber um conjuto heterogêneo de dados  
já um array (vamos ver adiante) NÃO !!!

In [10]:
m2 = [1, 2, 3.5, 1/3, 'a', 'como vai você?']
m2

[1, 2, 3.5, 0.3333333333333333, 'a', 'como vai você?']

In [11]:
m2[0]

1

### type(elemento da matriz) == qual é classe deste elemento?

In [12]:
type(m2[0])

int

### Veja como é fácil um loop (laço)

In [13]:
len(m2)

6

In [15]:
# com o for (loop) posso percorrer cada um dos elementos
for m in m2:
    # <tab> para identar dentro de um laço
    print(m)

1
2
3.5
0.3333333333333333
a
como vai você?


In [17]:
# \t == tabulador
# type() - é para achar o tipo de objeto

for m in m2:
    print(m, '\t\t\t', type(m))

1 			 <class 'int'>
2 			 <class 'int'>
3.5 			 <class 'float'>
0.3333333333333333 			 <class 'float'>
a 			 <class 'str'>
como vai você? 			 <class 'str'>


### O Python às vezes faz mágica ou confunde o usuário!

In [18]:
mat

[2, 3, 4, 5, 6, 7]

In [19]:
mat * 3

[2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7]

In [20]:
# isto não fucniona !
mat + 1

TypeError: can only concatenate list (not "int") to list

In [21]:
mat2 = [10, 11, 12, 13, 14, 15]
mat, mat2

([2, 3, 4, 5, 6, 7], [10, 11, 12, 13, 14, 15])

### Lista tem características próprias, e aqui mat + mat2 = union(mat, mat2)

In [22]:
mat + mat2

[2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15]

### Existe uma biblioteca para manipular matrizes e cálculo com números

  - Numpy: https://numpy.org/

In [24]:
### Chamando um biblioteca em python (ou pacote = package)
import numpy as np
### chamo numpy com o apelido np

In [25]:
mat, type(mat)

([2, 3, 4, 5, 6, 7], list)

### transformando a Lista em Array (numpy)

In [26]:
matn = np.array(mat)
matn

array([2, 3, 4, 5, 6, 7])

In [27]:
mat * 3

[2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7]

In [28]:
matn * 3

array([ 6,  9, 12, 15, 18, 21])

In [29]:
# erro !
mat + 1

TypeError: can only concatenate list (not "int") to list

In [30]:
matn + 1

array([3, 4, 5, 6, 7, 8])

In [31]:
matn2 = np.array(mat2)
matn, matn2

(array([2, 3, 4, 5, 6, 7]), array([10, 11, 12, 13, 14, 15]))

### Fazer uma soma de elemento por elemento

In [32]:
matn + matn2

array([12, 14, 16, 18, 20, 22])

### Numpy array exige que todos os elemnentos seja da mesma classe (type())

In [34]:
matn + ['aaa', 'bbb']

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

### Como você pode obsevar uma LISTA tem um comportamento diferente que uma Lista em Numpy